language: c
compiler: gcc
dist: bionic

before_install:
  - sudo apt-get install -y python-pip python-psutil
  - sudo -H pip install lit
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make smoketests
  - make tests
